{
 "title": "Global Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "instance", "label": "Cluster", "query": "IP Address" },
   {
    "name": "namespace",
    "label": "User",
    "query": "label_values(kube_namespace_labels{instance=\"$instance\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",instance=\"$instance\",container_name!=\"\",image!=\"\",exported_job=\"kubelet\"}[2m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", instance=\"$instance\", container_name!=\"\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(irate(container_fs_writes_bytes_total{namespace=\"$namespace\",instance=\"$instance\",image!=\"\",exported_job=\"kubelet\"}[2m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\",instance=\"$instance\",container_name!=\"\",image!=\"\",exported_job=\"kubelet\",interface=\"eth0\"}[2m]))",
     "legendFormat": "Download"
    },
    {
     "expr": "0-sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\",instance=\"$instance\",container_name!=\"\",image!=\"\",exported_job=\"kubelet\",interface=\"eth0\"}[2m]))",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}